# Generated by Django 3.2.3 on 2021-09-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-writing_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='writing_date',
        ),
    ]
